# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-frontend-static-files:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    defaults:
      run:
        working-directory: wine-one-frontend    

    steps:
    - uses: actions/checkout@v3
    - run: pwd
    - name: Use Node.js ${{ matrix.node-version }} in frontend
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: run npm commands in frontend 
      working-directory: wine-one-frontend
      run: |
        npm i
