# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        
    steps:
    - uses: actions/checkout@v3
    - name: Print working directory
      working-directory: wine-one-frontend
      run: pwd
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: wine-one-frontend/package-lock.json
    - name: Run npm commands    
      working-directory: wine-one-frontend  
      run: |
        npm ci
        npm run build --if-present
        mv build ../backend/static/
    - name: Use Node.js ${{ matrix.node-version }} in backend
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
    - name: Create dotenv file
      working-directory: backend
      run : |
        touch .env
        echo MONGO_URL="mongodb+srv://matt:${{ secrets.MONGO_SECRET }}@wineone.6sajobm.mongodb.net/?retryWrites=true&w=majority" >> .env
        echo SECRET=${{ secrets.SECRET }} >> .env
        echo PORT=1337 >> .env
    - name: run npm commands in backend
      working-directory: backend
      run: |
        npm i
        pm2 restart server
